apiVersion: v2
name: application
description: Sample web application for EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - web
  - nginx
  - demo
maintainers:
  - name: DevOps Team
    email: devops@example.com
