apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# ArgoCD Application Controller (handles sync)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-application-controller
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: argocd-application-controller
        image: quay.io/argoproj/argocd:v2.11.0
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
---
# Full install (apply this after namespace)
# curl -sSL -o install.yaml https://argoproj.github.io/argo-cd/install.yaml | \
# sed 's/1 replica/2 replicas/g' | kubectl apply -f -
