releases:
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: "0.7.2"
    values:
      - args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP
